In [61]:
import pandas as pd

In [62]:
df = pd.read_excel("teste.xlsx")
df.head(10)

,CODOCORRENCIA,CTE,EMPRESA,CALLCENTER,VIAGEM,CODPARC,CLIENTE,DATA_NEG,COD_VEICULO,PLACA,MOTORISTA,MOTORISTA2,CONTRATADO,CONTRATADO3,OCORRENCIA,VALOR,usuario_desp,centro_custo,STATUS_FINANCEIRO
0,103,3266,1,19,20,15,EBBA,2024-01-04,167,BEE7J93,2672,ANTONIO ELIZEU ANDRADE,2675,TRANS NAVI,PAGAMENTO CARGA/DESCARGA,-325.0,K.CASTRO,EMBARQUE ARAGUARI (LOTAÇÃO),Sem Rec. Gerada
1,103,3266,1,19,20,15,EBBA,2024-01-04,167,BEE7J93,2672,ANTONIO ELIZEU ANDRADE,2675,TRANS NAVI,PAGAMENTO CARGA/DESCARGA,-27.0,K.MELO,EMBARQUE ARAGUARI (LOTAÇÃO),Sem Rec. Gerada
2,104,3266,1,19,20,15,EBBA,2024-01-04,167,BEE7J93,2672,ANTONIO ELIZEU ANDRADE,2675,TRANS NAVI,COBRANÇA DESCARGA - CTE,352.0,K.MELO,EMBARQUE ARAGUARI (LOTAÇÃO),Sem Rec. Gerada
3,103,3515,1,32,24,15,EBBA,2024-01-05,170,CUD6B58,2682,ADEMIR DONIZETI CAETANO,2682,ADEMIR DONIZETI CAETANO,PAGAMENTO CARGA/DESCARGA,-308.0,K.CASTRO,EMBARQUE ARAGUARI (LOTAÇÃO),Sem Rec. Gerada
4,104,3515,1,32,24,15,EBBA,2024-01-05,170,CUD6B58,2682,ADEMIR DONIZETI CAETANO,2682,ADEMIR DONIZETI CAETANO,COBRANÇA DESCARGA - CTE,308.0,K.CASTRO,EMBARQUE ARAGUARI (LOTAÇÃO),Sem Rec. Gerada
5,103,3589,1,38,26,663,SIG,2024-01-05,149,MPW9571,2627,ANGELO MARCELO MARTINS,2625,CLEIDSON CANDIDO RIBEIRO,PAGAMENTO CARGA/DESCARGA,-352.0,K.CASTRO,EMBARQUE ARAGUARI (LOTAÇÃO),Sem Rec. Gerada
6,103,3949,1,60,13,15,EBBA,2024-01-06,158,IHX4I61,2652,VALDIR CORREA DE SA,2651,CAROLINA LAIS ARANDA,PAGAMENTO CARGA/DESCARGA,-408.0,K.CASTRO,EMBARQUE ARAGUARI (LOTAÇÃO),Sem Rec. Gerada
7,104,3949,1,60,13,15,EBBA,2024-01-06,158,IHX4I61,2652,VALDIR CORREA DE SA,2651,CAROLINA LAIS ARANDA,COBRANÇA DESCARGA - CTE,408.0,K.CASTRO,EMBARQUE ARAGUARI (LOTAÇÃO),Sem Rec. Gerada
8,103,3960,1,65,68,15,EBBA,2024-01-06,97,HHK3I19,1414,ROMARIO SELBMANN JUNIOR,1413,51.039.921 ROMARIO SELBMANN JUNIOR,PAGAMENTO CARGA/DESCARGA,-300.0,K.CASTRO,EMBARQUE ARAGUARI (LOTAÇÃO),Sem Rec. Gerada
9,104,3960,1,65,68,15,EBBA,2024-01-06,97,HHK3I19,1414,ROMARIO SELBMANN JUNIOR,1413,51.039.921 ROMARIO SELBMANN JUNIOR,COBRANÇA DESCARGA - CTE,300.0,K.CASTRO,EMBARQUE ARAGUARI (LOTAÇÃO),Sem Rec. Gerada

In [64]:
pivot_table = pd.pivot_table(
    data=df,
    values='VALOR',     # coluna com os valores numéricos a serem agregados
    index='CLIENTE',         # coluna(s) para usar como índice na nova tabela
    columns='Mes_Ano',   # Usa a nova coluna 'Mes_Ano'
    aggfunc='sum',
    margins=True,        # Adiciona o total geral
    margins_name='Total Geral'  # Nomeia o total geral
)
pivot_table.fillna(0, inplace=True)

pivot_table.columns = pivot_table.columns.strftime('%b/%y').str.upper()
# Função para formatar valores negativos em vermelho
def color_negative_red(val):
    color = 'red' if val < 0 else 'black'
    return f'color: {color}'

# Aplicar o estilo na tabela pivô usando `map`
tabela_pivo_style = pivot_table.style.map(color_negative_red)

tabela_pivo_style

KeyError: 'Mes_Ano'